# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler: '%kernel.debug%'
    clients:
        avenir_geopo:
            lazy: true
            config:
                base_uri: 'https://sandbox.ar24.fr'
                timeout: 0
                headers:
                    Accept: application/json
                    Content-Type: application/json
            middleware: ['ar24_middleware']
